[package]
name = "query-opt-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
typed-generational-arena = "0.2.5"
slab = "0.4.9"

[dev-dependencies]
divan = "0.1"
rand = "0.8"

[[bench]]
name = "tables"
harness = false
