version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "crates/"
    schedule:
      interval: "weekly"
    groups:
      cargo-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
