[package]
name = "emdb"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.38", features = ["full"] }
typed-arena = "2.0.2"
typed-generational-arena = "0.2"
proc-macro2 = "1.0"
proc-macro-error = "1.0.4"
chumsky = "0.9.3"
