[package]
name = "enumtrait"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-error = "1.0.4"
syn = { version = "2.0.45", features = ["full", "extra-traits"] }
quote = "1.0.33"