[workspace]
resolver = "2"
members = ["combi", "emdb", "enumtrait", "pulpit", "pulpit_gen", "pulpit_macro", "quote_debug"]

[workspace.package]
homepage = "https://github.com/OliverKillane/emDB"
repository = "https://github.com/OliverKillane/emDB"
license-file = "LICENSE"
